confidence: 0.01 
input_images_dir:  images # files to predict 
output_dir : output
model_checkpoint: checkpoints/best.pt
experiment_name: october30_final
visualization: true 
class_dict: 
    0: Caption
    1: Footnote
    2: Formula
    3: List-item
    4: Page-footer
    5: Page-header
    6: Picture
    7: Section-header
    8: Table
    9: Text
    10: Title
